#日志配置
server:
  port: 8002
  session:
    timeout: 1800 #秒

spring:
  application:
    name: sure-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:sure/**/*.xml

logging:
  config: classpath:logback-spring.xml






