#日志配置
server:
  port: 8081
spring:
  application:
    name: sure-admin

  freemarker:
    cache: false
    request-context-attribute: ctx
    template-loader-path: classpath:/templates
    #前缀
    #suffix: .go
    #后缀
    #prefix: /htm/
    prefer-file-system-access: false
    allow-request-override: false
    check-template-location: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #数据库配置
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 6000
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
logging:
  config: classpath:config/logback-spring.xml
  path: f:tool/project/logs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
