#日志配置
server:
  port: 8080
spring:
  application:
    name: sure-gate
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    favicon:
      enabled: false
logging:
  config: classpath:logback-spring.xml


zuul:
  sensitive-headers:
  add-host-header: true
  host:
    socket-timeout-millis: 120000
    connect-timeout-millis: 120000
  routes:
    config:
      path: /**/config/**
      url: http://127.0.0.1:8002/
    admin:
      path: /admin/**
      url: http://127.0.0.1:8004/


